version: '3.4'

services:
  reviews-module:
    image: reviews-module
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3003
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 ./server/index.js